-- =====================================================================
-- Source (OLTP) database schema: "sales"
-- Runs automatically on first container start (docker-entrypoint-initdb.d).
--
-- Design notes
--   * Structural integrity is enforced here: PKs, FKs, NOT NULL, CHECKs.
--   * Semantic problems (negative totals, future-dated orders, duplicate people
--     with different e-mail casing, totals that do not match line items) are NOT
--     blocked, because real operational systems rarely enforce every business
--     rule. The Silver layer and data-quality framework must catch them.
--   * Every table has created_at / updated_at (UTC). updated_at is maintained by a
--     trigger (003_triggers.sql) and is the watermark for incremental extraction.
--   * Reference data (countries) arrives as a CSV file, not from this database,
--     so country codes here are not foreign keys.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS sales;

CREATE TABLE sales.customers (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(40),
    country_code  CHAR(2)      NOT NULL,
    city          VARCHAR(120),
    segment       VARCHAR(20)  NOT NULL DEFAULT 'consumer',
    signup_date   DATE         NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_segment CHECK (segment IN ('consumer', 'small_business', 'enterprise')),
    CONSTRAINT ck_customers_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE sales.products (
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(40)    NOT NULL,
    product_name  VARCHAR(200)   NOT NULL,
    category      VARCHAR(50)    NOT NULL,
    unit_price    NUMERIC(12, 2) NOT NULL,
    unit_cost     NUMERIC(12, 2) NOT NULL,
    currency      CHAR(3)        NOT NULL DEFAULT 'USD',
    is_active     BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_price CHECK (unit_price >= 0),
    CONSTRAINT ck_products_cost CHECK (unit_cost >= 0),
    CONSTRAINT ck_products_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE sales.orders (
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT         NOT NULL REFERENCES sales.customers (customer_id),
    order_date       TIMESTAMPTZ    NOT NULL,
    status           VARCHAR(20)    NOT NULL,
    currency         CHAR(3)        NOT NULL,
    shipping_country CHAR(2)        NOT NULL,
    -- Deliberately no sign check: negative totals exist in the wild (bad refunds, bugs).
    total_amount     NUMERIC(14, 2) NOT NULL,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_orders_status CHECK (
        status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'returned')
    ),
    CONSTRAINT ck_orders_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE sales.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT         NOT NULL REFERENCES sales.orders (order_id),
    product_id    BIGINT         NOT NULL REFERENCES sales.products (product_id),
    quantity      INTEGER        NOT NULL,
    unit_price    NUMERIC(12, 2) NOT NULL,   -- in the order's currency
    discount_pct  NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_discount CHECK (discount_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_order_items_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE sales.payments (
    payment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT         NOT NULL REFERENCES sales.orders (order_id),
    payment_method VARCHAR(30)    NOT NULL,
    payment_status VARCHAR(20)    NOT NULL,
    -- Deliberately no sign check (see orders.total_amount).
    amount         NUMERIC(14, 2) NOT NULL,
    currency       CHAR(3)        NOT NULL,
    paid_at        TIMESTAMPTZ,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_payments_method CHECK (
        payment_method IN ('card', 'paypal', 'bank_transfer', 'apple_pay', 'gift_card')
    ),
    CONSTRAINT ck_payments_status CHECK (
        payment_status IN ('pending', 'completed', 'failed', 'refunded')
    ),
    CONSTRAINT ck_payments_paid_at CHECK (payment_status <> 'completed' OR paid_at IS NOT NULL),
    CONSTRAINT ck_payments_updated_after_created CHECK (updated_at >= created_at)
);
